local map = vim.keymap.set
local opts = { noremap = true, silent = true }

map("n", "<C-s>", "<cmd>w<cr>", { desc = "Save file" })
map("i", "<C-s>", "<Esc><cmd>w<cr>", { desc = "Save file" })
map("n", "<C-z>", "u", { desc = "Undo" })
map("n", "<C-S-z>", "<C-r>", { desc = "Redo" })
map("n", "<C-/>", "gcc", { desc = "Toggle comment" })
map("v", "<C-/>", "gc", { desc = "Toggle comment (visual)" })
map("n", "<C-p>", function()
  require("snacks.picker").files()
end, { desc = "Find file" })
map("n", "<C-S-f>", function()
  require("snacks.picker").grep()
end, { desc = "Find in files" })
map("n", "<C-S-e>", function()
  require("snacks.picker").git_files()
end, { desc = "Find in git files" })
map("n", "<C-b>", function()
  require("snacks").terminal.toggle()
end, { desc = "Toggle terminal" })
map("t", "<C-b>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
map("n", "<C-A>", function()
  require("opencode").ask()
end, { desc = "Ask opencode" })
map("n", "<C-S-p>", "<cmd>Telescope commands<cr>", { desc = "Command palette" })
map("n", "<C-Shift-P>", "<cmd>Telescope commands<cr>", { desc = "Command palette" })
map("n", "<leader>ff", function()
  require("snacks.picker").files()
end, { desc = "Find files" })
map("n", "<leader>fg", function()
  require("snacks.picker").grep()
end, { desc = "Grep in files" })
map("n", "<leader>fb", function()
  require("snacks.picker").buffers()
end, { desc = "Find buffers" })
map("n", "<leader>fo", function()
  require("snacks.picker").oldfiles()
end, { desc = "Find recent files" })
map("n", "<leader>fw", function()
  require("snacks.picker").grep_word()
end, { desc = "Find word under cursor" })
map("n", "<leader>gc", "<cmd>Telescope git_commits<cr>", { desc = "Git commits" })
map("n", "<leader>gs", "<cmd>Telescope git_status<cr>", { desc = "Git status" })
map("n", "<leader>gd", "<cmd>DiffviewOpen<cr>", { desc = "Git diff" })
map("n", "<leader>gb", "<cmd>Telescope git_branches<cr>", { desc = "Git branches" })
map("n", "<leader>rn", function()
  vim.lsp.buf.rename()
end, { desc = "Rename symbol" })
map("n", "<leader>ca", function()
  vim.lsp.buf.code_action()
end, { desc = "Code action" })
map("n", "<leader>cd", function()
  vim.diagnostic.open_float()
end, { desc = "Show diagnostics" })
map("n", "<leader>cn", function()
  vim.diagnostic.goto_next()
end, { desc = "Next diagnostic" })
map("n", "<leader>cp", function()
  vim.diagnostic.goto_prev()
end, { desc = "Prev diagnostic" })
map("n", "<leader>cl", function()
  vim.lsp.codelens.run()
end, { desc = "Run codelens" })
map("n", "gd", function()
  vim.lsp.buf.definition()
end, { desc = "Go to definition" })
map("n", "gD", function()
  vim.lsp.buf.declaration()
end, { desc = "Go to declaration" })
map("n", "gi", function()
  vim.lsp.buf.implementation()
end, { desc = "Go to implementation" })
map("n", "gr", function()
  vim.lsp.buf.references()
end, { desc = "Find references" })
map("n", "K", function()
  vim.lsp.buf.hover()
end, { desc = "Hover documentation" })
map("n", "<leader>td", function()
  vim.lsp.buf.type_definition()
end, { desc = "Type definition" })
map("n", "<leader>q", "<cmd>qa<cr>", { desc = "Quit all" })
map("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit all" })
map("n", "<leader>qw", "<cmd>wq<cr>", { desc = "Save and quit" })
map("n", "<leader>qc", "<cmd>q!<cr>", { desc = "Force quit" })
map("n", "<leader>tt", function()
  require("snacks").terminal.toggle()
end, { desc = "Toggle terminal" })
map("n", "<leader>to", function()
  require("snacks").terminal.open()
end, { desc = "Open terminal" })
map("n", "<leader>tw", function()
  require("snacks").terminal.toggle()
end, { desc = "Toggle terminal in window" })
map("n", "<leader>xx", "<cmd>Trouble toggle<cr>", { desc = "Toggle trouble" })
map("n", "<leader>xd", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })
map("n", "<leader>xq", "<cmd>copen<cr>", { desc = "Quickfix list" })
map("n", "<leader>xl", "<cmd>lopen<cr>", { desc = "Location list" })
map("n", "<C-Left>", "<C-w>h", { desc = "Move to left window" })
map("n", "<C-Right>", "<C-w>l", { desc = "Move to right window" })
map("n", "<C-Up>", "<C-w>k", { desc = "Move to upper window" })
map("n", "<C-Down>", "<C-w>j", { desc = "Move to lower window" })
map("n", "<C-Tab>", "<cmd>BufferLineCycleNext<cr>", { desc = "Next buffer" })
map("n", "<C-S-Tab>", "<cmd>BufferLineCyclePrev<cr>", { desc = "Previous buffer" })
map("n", "<leader>e", function()
  require("oil").open()
end, { desc = "Open file explorer" })
map("n", "<leader>-", function()
  require("oil").open()
end, { desc = "Open file explorer" })
map("n", "<leader>h", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
map("n", "<leader>u", "<cmd>UndotreeToggle<cr>", { desc = "Toggle undo tree" })
map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move selection down" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move selection up" })
map("n", "<leader>af", function()
  vim.lsp.buf.format({ async = true })
end, { desc = "Format file" })
map("n", "<leader>as", function()
  vim.lsp.buf.signature_help()
end, { desc = "Signature help" })
map("n", "<leader>ai", function()
  vim.lsp.buf.incoming_calls()
end, { desc = "Incoming calls" })
map("n", "<leader>ao", function()
  vim.lsp.buf.outgoing_calls()
end, { desc = "Outgoing calls" })
map("n", "<leader>wa", function()
  vim.lsp.buf.add_workspace_folder()
end, { desc = "Add workspace folder" })
map("n", "<leader>wr", function()
  vim.lsp.buf.remove_workspace_folder()
end, { desc = "Remove workspace folder" })
map("n", "<leader>wl", function()
  print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end, { desc = "List workspace folders" })
map("n", "<leader>ds", function()
  require("telescope.builtin").lsp_document_symbols()
end, { desc = "Document symbols" })
map("n", "<leader>ws", function()
  require("telescope.builtin").lsp_dynamic_workspace_symbols()
end, { desc = "Workspace symbols" })
map("n", "<leader>la", function()
  vim.g.autopairs_enabled = not vim.g.autopairs_enabled
  if vim.g.autopairs_enabled then
    require("nvim-autopairs").enable()
  else
    require("nvim-autopairs").disable()
  end
end, { desc = "Toggle autopairs" })
map("n", "<leader>lw", function()
  vim.wo.wrap = not vim.wo.wrap
end, { desc = "Toggle wrap" })
map("n", "<leader>lc", function()
  vim.wo.cursorline = not vim.wo.cursorline
end, { desc = "Toggle cursorline" })
map("n", "<leader>li", function()
  vim.wo.relativenumber = not vim.wo.relativenumber
end, { desc = "Toggle relative numbers" })
map("n", "<leader>lf", function()
  vim.wo.foldenable = not vim.wo.foldenable
end, { desc = "Toggle folds" })
map("n", "<leader>sr", function()
  vim.cmd("%s/\\v//gc")
end, { desc = "Search and replace" })
map("n", "<leader>sc", function()
  vim.cmd("%s/\\v//g")
end, { desc = "Search and replace all" })
